server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/**
            - Header=X-Role, ^user$
          filters:
            - AddRequestHeader=X-Mentoring, i-Keeper

        - id: admin-service
          uri: http://localhost:8082/
          predicates:
            - Path=/**
            - Header=X-Role, ^admin$
          filters:
            - AddRequestHeader=X-Mentoring, i-Keeper
